#logging:
#  level:
#    root: debug




server:
  port: 8002
  
  
spring:
  application:
    name: demo-zipkin-dependencia
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: "(^cleanup.*)"
    
      
      
      